### PR TITLE
TL/MLX5: disable mcast for thread multiple

### PR DESCRIPTION
**Pull request by MamziB**
TL/MLX5: disable mcast for thread multiple

### CODE REVIEW

**Review by samnordmann — APPROVED** [review]

**Comment by janjust** [comment]
@MamziB Does this fix any of the redmine issues?

**Review by Sergei-Lebedev — APPROVED** [review]

**Comment by janjust** [comment]
bot:retest

**Comment by MamziB** [comment]
@janjust yes, the data validation issue.

**Comment by janjust** [comment]
ah perfect

**Comment by artemry-nv** [comment]
bot:retest

**Pull request merged**
