### PR TITLE
DOCS: aligning conf file

### PR DESCRIPTION
**Pull request by shimmybalsam**
## What
Aligning ucc.conf to be similar to that in ucc_private.

## Why ?
For future users who use this file as a template/example for their configurations. This way they will see up to date multiple architectures tuning.

### CODE REVIEW

**Comment by manjugv** [comment]
@shimmybalsam should we call this ucc_ompi.conf since we have OMPI variables?

**Comment by shimmybalsam** [comment]
> @shimmybalsam should we call this ucc_ompi.conf since we have OMPI variables?

@manjugv  I don't think so. I think it should be a unified example file for any user.
The OMPI prefix was added in ucc_private due to interference of those specific variables in certain cases (for example pytorch). 
For this file I can remove OMPI from the variables so that they will start with UCC. What do you think?

**Comment by manjugv** [comment]
> > @shimmybalsam should we call this ucc_ompi.conf since we have OMPI variables?
> 
> @manjugv I don't think so. I think it should be a unified example file for any user. The OMPI prefix was added in ucc_private due to interference of those specific variables in certain cases (for example pytorch). For this file I can remove OMPI from the variables so that they will start with UCC. What do you think?

Yes, that sounds better.

**Comment by shimmybalsam** [comment]
> > > @shimmybalsam should we call this ucc_ompi.conf since we have OMPI variables?
> > 
> > 
> > @manjugv I don't think so. I think it should be a unified example file for any user. The OMPI prefix was added in ucc_private due to interference of those specific variables in certain cases (for example pytorch). For this file I can remove OMPI from the variables so that they will start with UCC. What do you think?
> 
> Yes, that sounds better.

OK fixed.
@manjugv @Sergei-Lebedev please rereview thanks.

**Review by Sergei-Lebedev — APPROVED** [review]

**Review by manjugv — APPROVED** [review]

**Comment by shimmybalsam** [comment]
bot:retest

**Comment by shimmybalsam** [comment]
bot:retest

**Comment by shimmybalsam** [comment]
bot:retest

**Pull request merged**
