### PR TITLE
API: Changing team destroy semantics from blocking to nonblocking

### PR DESCRIPTION
**Pull request by manjugv**
Addressing issue #56

### CODE REVIEW

**Comment by vspetrov** [comment]
@manjugv 1 question: do we say that team_destroy "can be non-blockin" ie it may not complete upon call return, OR we say that it is guaranteed to be non-blocking ? What if some TLs/Cls can not support that? E.g., right now we have non-blocking team creation but NCCL can not support that since nccl comm creation is a blocking collective call.

**Comment by manjugv** [comment]
> @manjugv 1 question: do we say that team_destroy "can be non-blockin" ie it may not complete upon call return, OR we say that it is guaranteed to be non-blocking ? What if some TLs/Cls can not support that? E.g., right now we have non-blocking team creation but NCCL can not support that since nccl comm creation is a blocking collective call.

Non-blocking : On return there is no guarantee that it is complete. If implementations block on non-blocking calls and complete, it is not wrong, but it is just a low-quality implementation.

**Comment by vspetrov** [comment]
I see that we don't introduce ucc_team_destroy_nb api but rather declaring ucc_team_destroy new semantics. Am i right that the user how wants to destroy the team need to call:
```
    ucc_status_t status;
    while (UCC_INPROGRESS == (status = ucc_team_destroy_single(team))) {
    |   ;
    }
```
do we need some blocking helper fn for user in ucc.h?
smth like
``` 
static inline ucc_team_destroy_and_wait(team) {
while ()...
}
```

**Comment by manjugv** [comment]
> I see that we don't introduce ucc_team_destroy_nb api but rather declaring ucc_team_destroy new semantics. Am i right that the user how wants to destroy the team need to call:
> 
> ```
>     ucc_status_t status;
>     while (UCC_INPROGRESS == (status = ucc_team_destroy_single(team))) {
>     |   ;
>     }
> ```
> 
> do we need some blocking helper fn for user in ucc.h?
> smth like
> 
> ```
> static inline ucc_team_destroy_and_wait(team) {
> while ()...
> }
> ```

You are correct Val, I was hoping we could do the earlier with the while loop. Helper function - should it be a part of API? we don't really add any value, if we implement in the library.

**Comment by vspetrov** [comment]
> > I see that we don't introduce ucc_team_destroy_nb api but rather declaring ucc_team_destroy new semantics. Am i right that the user how wants to destroy the team need to call:
> > ```
> >     ucc_status_t status;
> >     while (UCC_INPROGRESS == (status = ucc_team_destroy_single(team))) {
> >     |   ;
> >     }
> > ```
> > 
> > 
> > do we need some blocking helper fn for user in ucc.h?
> > smth like
> > ```
> > static inline ucc_team_destroy_and_wait(team) {
> > while ()...
> > }
> > ```
> 
> You are correct Val, I was hoping we could do the earlier with the while loop. Helper function - should it be a part of API? we don't really add any value, if we implement in the library.

agree

**Review by vspetrov — APPROVED** [review]

**Comment by manjugv** [comment]
@Sergei-Lebedev Any comments?

**Review by Sergei-Lebedev — APPROVED** [review]

**Pull request merged**
