### PR TITLE
EC/CPU: fix error message

### PR DESCRIPTION
**Pull request by Sergei-Lebedev**
## What
Fix typo in error message

### CODE REVIEW

**Review by samnordmann — APPROVED** [review]

**Comment by edgargabriel** [comment]
@Sergei-Lebedev it seems to me that we are running into the same issue with UCX that we had with UCC and was fixed in PR https://github.com/openucx/ucc/pull/804 . The hip header file generates a warning when compiled with clang, which in itself is harmless, but because  all warnings are treated as errors, the compilation fails. I will see what we can do about it. One option would be to compile UCX with gcc instead of clang (since we are not truly interested in running clang-tidy on ucx in this CI, but just on UCC)

**Comment by edgargabriel** [comment]
@Sergei-Lebedev it is more complicated: compiling UCX with gcc instead of clang fixes the first issue. There is however another issue in that we need clang-14 to compile UCC  for the rocm/rccl components. With clang-12 we ran into another issue in the hip header files where a flag to disable some warnings is not recognized (in the hip header files) and generates a warning again:

```
In file included from /opt/rocm/include/hip/hip_runtime_api.h:483:
/opt/rocm/include/hip/surface_types.h:30:34: error: unknown warning group '-Wreserved-identifier', ignored [-Werror,-Wunknown-warning-option]
#pragma clang diagnostic ignored "-Wreserved-identifier"
```

With clang-14 this error is not observed, and UCC compiles correctly. However clang-tidy with clang-14 fails, see 

https://github.com/openucx/ucc/actions/runs/6264142779/job/17010173739?pr=846

Not sure what our options are. If you want I can convert Clang-tidy-rocm into a rocm compilation only (without the clang-tidy part), which would also still have some value to ensure that a pr is compiled also against the rocm components. Let me know what you suggest.

**Comment by edgargabriel** [comment]
the problem is of course triggered by the release of rocm-5.7 a few days ago. The script fetches the most recent rocm version. I can also explore whether I could fetch a fixed rocm version instead, hence go back to rocm-5.6 for example.

**Comment by edgargabriel** [comment]
https://github.com/openucx/ucc/pull/846 fixes the ROCM-linter compilation issue, by using rocm 5.6.1 (instead of the newest version), and compiling ucx with gcc instead of clang.

**Review by manjugv — APPROVED** [review]

**Pull request merged**
