### PR TITLE
DOCS: update coll_args tables

### PR DESCRIPTION
**Pull request by vspetrov**
## What
Update doc coll_args tables: adding mem_type field.

Result: 
[ucc.pdf](https://github.com/openucx/ucc/files/6043510/ucc.pdf)

### CODE REVIEW

**Comment by manjugv** [comment]
@vspetrov Have we defined the Fan-in and Fan-out routines? Without that, I'm not sure how to interpret that part of the table.

**Comment by vspetrov** [comment]
> @vspetrov Have we defined the Fan-in and Fan-out routines? Without that, I'm not sure how to interpret that part of the table.

Fanin - is 0 byte reduce to root, ie, all ranks notify the root their presence.
Fanout is inverse of that - 0 byte bcast from root.

MPI does not have those. We use them internally in multiple cases to build more complex algorithms. If we think we don't need to expose them to user we can remove them.

**Comment by manjugv** [comment]
Got it, I think this would be useful for users building custom/hierarchies on top of UCC as well. This shows the need for documenting collective semantics. We need to make it explicit somewhere. I'm not sure what is the correct place. Spec or header ?

**Comment by manjugv** [comment]
Overall, the table looks fine to me.

**Review by manjugv — APPROVED** [review]

**Comment by manjugv** [comment]
@vspetrov Did you check the documentation in html format? I did require png format files for html documentation. I was wondering, if you had the same issue.

**Comment by vspetrov** [comment]
> Got it, I think this would be useful for users building custom/hierarchies on top of UCC as well. This shows the need for documenting collective semantics. We need to make it explicit somewhere. I'm not sure what is the correct place. Spec or header ?

i would say "spec". too long descriptions in the header make it look too complicated imho.

**Comment by vspetrov** [comment]
> @vspetrov Did you check the documentation in html format? I did require png format files for html documentation. I was wondering, if you had the same issue.

:+1 added "png" tables for html

**Comment by bureddy** [comment]
Don't we need allreduce entry in the table? (basically saying root will be ignored)

**Comment by vspetrov** [comment]
> Don't we need allreduce entry in the table? (basically saying root will be ignored)

@bureddy i don't undertand. allreduce IS there and the "root" flag is not set in the table. plz recheck and clarify what you meant

**Comment by bureddy** [comment]
> > Don't we need allreduce entry in the table? (basically saying root will be ignored)
> 
> @bureddy i don't undertand. allreduce IS there and the "root" flag is not set in the table. plz recheck and clarify what you meant

my bad. looking the wrong table.

**Review by bureddy — APPROVED** [review]

**Pull request merged**
