### PR TITLE
TL/UCP: add reorder ranks in allreduce kn

### PR DESCRIPTION
**Pull request by shimmybalsam**
## What
Add reorder ranks in allreduce kn

## How
ranks/peers already using basic 1:1 mapping in default task->subset.map, so no change needed in start/progress, only setting task->subset.map to correct reordering map in init is needed.

### CODE REVIEW

**Comment by shimmybalsam** [comment]
image

**Review by samnordmann — APPROVED** [review]

**Comment by Sergei-Lebedev** [comment]
@shimmybalsam can you please run on a larger scale and up to 128MB

**Comment by shimmybalsam** [comment]
> @shimmybalsam can you please run on a larger scale and up to 128MB

Sure but just out of general interest - why? We only use allreduce_knomial for small msgsize.

**Comment by Sergei-Lebedev** [comment]
> > @shimmybalsam can you please run on a larger scale and up to 128MB
> 
> Sure but just out of general interest - why? We only use allreduce_knomial for small msgsize.

it's not clear from the graph that we got any improvements

**Comment by shimmybalsam** [comment]
> > > @shimmybalsam can you please run on a larger scale and up to 128MB
> > 
> > 
> > Sure but just out of general interest - why? We only use allreduce_knomial for small msgsize.
> 
> it's not clear from the graph that we got any improvements

@Sergei-Lebedev I ran up to 4MB and there seems to be no improvement:

image


I also checked on 4 and 8 nodes and also on rock (2 4 and 8 nodes) , 1 ppn and full ppn (28 on jazz , 64 on rock) - still no imporvemnt.

But, when running non full ppn (but thats larger then 1) there is a positive effect.
For example here are the results for 20 ppn on 4 and 8 nodes on jazz and 34 ppn on 4 and 8 nodes on rock:

image

**Comment by shimmybalsam** [comment]
bot:retest

**Review by Sergei-Lebedev — APPROVED** [review]

**Pull request merged**
