### PR TITLE
EC/ROCM: PROD overload issue for HIP complex

### PR DESCRIPTION
**Pull request by PedramAlizadeh**
resolving the compilation issue for overloading the multiplication operator for double and float hip complex type.

## What
This PR resolves the compilation error for the ec_rocm_reduce.cu file. 

## Why ?
The compilation error is due to the use of hip complex/vector types with operators. This change in the hip compiler results in the "overloaded operator '*' is ambiguous" error at compilation time. 

## How ?
The PR manually calls the appropriate operators for hip complex types and hence resolves the ambiguity of the overloaded multiplication operator.

### CODE REVIEW

**Comment by Sergei-Lebedev** [comment]
ok to test

**Comment by PedramAlizadeh** [comment]
@edgargabriel

**Comment by edgargabriel** [comment]
@manjugv @Sergei-Lebedev this is the fix that I mentioned in the meeting last Wednesday. We would like to bring this over to the 1.2 release as well.  The code compiles again with this fix on upcoming ROCm release and tests are also passing. We are still doing some more testing, but I think the pr is good to be reviewed from our side.

**Review by Sergei-Lebedev — APPROVED** [review]

**Comment by manjugv** [comment]
@PedramAlizadeh Can you please fix the commit title? There is code style error and also some formating. 

```
"Commit title is too long: 54
[49](https://github.com/openucx/ucc/actions/runs/5004329937/jobs/8971128680?pr=775#step:4:50)
Bad commit title: 'EC/ROCM: Multiplication overload issue for HIP complex'"
```

**Comment by PedramAlizadeh** [comment]
Hi there,
the CI failure is not related to this pr, would it be possible to restart it pls?
Thanks!

**Review by manjugv — APPROVED** [review]

**Comment by manjugv** [comment]
@PedramAlizadeh Please also port to v1.2 branch

**Comment by edgargabriel** [comment]
@manjugv done, see https://github.com/openucx/ucc/pull/783

**Pull request merged**
