### PR TITLE
TEST: Updated torch_ucc repo, fixed cmake issue

### PR DESCRIPTION
**Pull request by artemry-nv**
Signed-off-by: artemry-nv <artemry@nvidia.com>

## What
Updated torch_ucc repo, fixed cmake issue

## Why ?
CI failed.

### CODE REVIEW

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
@vspetrov @Sergei-Lebedev @manjugv @bureddy could you please merge this PR to restore Jenkins CI?
UCC unit tests are temporarily disabled because they break CI cluster (need to investigate).

**Review by vspetrov — APPROVED** [review]

**Review by Sergei-Lebedev — APPROVED** [review]

**Pull request merged**
