### PR TITLE
Update gitignore file

### PR DESCRIPTION
**Pull request by edgargabriel**
## What
Update the .gitignore file to exclude files generated during configury and compilation

## Why ?
makes the output of 

git status

easier to parse.

##How
no code change required for this commit.

### CODE REVIEW

**Review by Sergei-Lebedev — APPROVED** [review]
can you pls add following vscode files to ignore list
```
.vscode
*.code-workspace
```

**Comment by Sergei-Lebedev** [comment]
ok to test

**Review by vspetrov — APPROVED** [review]

**Comment by edgargabriel** [comment]
> can you pls add following vscode files to ignore list
> 
> ```
> .vscode
> *.code-workspace
> ```

done

**Comment by Sergei-Lebedev** [comment]
@edgargabriel pls fix commit title, it should include prefix, for example "CODESTYLE: update gitignore file"

**Comment by edgargabriel** [comment]
> @edgargabriel pls fix commit title, it should include prefix, for example "CODESTYLE: update gitignore file"

@Sergei-Lebedev I've updated the commit title, I don't think I see however a way to update the pr title itself.

**Comment by Sergei-Lebedev** [comment]
> > @edgargabriel pls fix commit title, it should include prefix, for example "CODESTYLE: update gitignore file"
> 
> @Sergei-Lebedev I've updated the commit title, I don't think I see however a way to update the pr title itself.

thanks, CI checks only commit tittle, PR title doesn't matter

**Pull request merged**
