### PR TITLE
TL/UCP: enable UCX active messages

### PR DESCRIPTION
**Pull request by gvallee**
## What
Enable UCX active messages.

## Why ?
A plugin is using UCX active messages which can only be enabled if the feature is activated when calling `ucp_init()`.

## How ?
N/A

### CODE REVIEW

**Comment by manjugv** [comment]
Do you need this in v1.0x branch ?

**Review by manjugv — APPROVED** [review]

**Comment by vspetrov** [comment]
@gvallee My only concern is: does requesting AM support has any effect on performance or resource consumption of UCX? If yes, then we probably want to make it conditional (ie, if requested by plugin).

**Comment by gvallee** [comment]
> Do you need this in v1.0x branch ?

It can wait until 1.1.x or later.

**Comment by gvallee** [comment]
> @gvallee My only concern is: does requesting AM support has any effect on performance or resource consumption of UCX? If yes, then we probably want to make it conditional (ie, if requested by plugin).

The UCX team told us that it is just fine and i did not ever see any performance degradation due to it. Algorithms benefiting from AM can even be more efficient than similar ones relying on TM. Did you experience such a performance degradation?

**Review by vspetrov — APPROVED** [review]

**Review by Sergei-Lebedev — APPROVED** [review]

**Pull request merged**
