### PR TITLE
API: Add hints for coll args

### PR DESCRIPTION
**Pull request by manjugv**
Reworking #624 , so the hints are in a different structure.

### CODE REVIEW

**Comment by vspetrov** [comment]
Just a thought: this increases our coll_args another 8 bytes, which might make it go beyond the next cache line (and several internal data structs that incapsulate coll_args) - could some one check if that is true (@shimmybalsam this could affect super low latency sensitive benches like tl/shm)

**Review by BrodyWilliams — APPROVED** [review]

**Comment by shimmybalsam** [comment]
> Just a thought: this increases our coll_args another 8 bytes, which might make it go beyond the next cache line (and several internal data structs that incapsulate coll_args) - could some one check if that is true (@shimmybalsam this could affect super low latency sensitive benches like tl/shm)

@vspetrov can you please elaborate? From what I know, our ctrl size in tl/shm is 256 deducted by sizeof(ucc_tl_shm_ctrl_t) where sizeof(ucc_tl_shm_ctrl_t) is 32. so we have 224 bytes left for data in small msgsize colls. And we don't specifically regard coll_args.

**Comment by BrodyWilliams** [comment]
@shimmybalsam - Have you had a chance to test if this affects your performance yet?

**Comment by shimmybalsam** [comment]
> 

Not yet, will update here once I do.

**Comment by shimmybalsam** [comment]
> @shimmybalsam - Have you had a chance to test if this affects your performance yet?

@BrodyWilliams Not yet, will update here once I do.

**Review by vspetrov — APPROVED** [review]

**Comment by BrodyWilliams** [comment]
> 

Great. Thanks!

**Comment by manjugv** [comment]
@Sergei-Lebedev , @bureddy Can you review and let me know any comments? Thanks.

**Comment by Sergei-Lebedev** [comment]
@vspetrov @manjugv what about saving 64 bits in coll_args structures  by renumbering those flags, i.e. we keep uint64_t flags only but define two disjoint enums. Also we can introduce aliases for contig buffers flags UCC_COLL_ARGS_HINT_CONTIG_SRC_BUFFER and UCC_COLL_ARGS_HINT_CONTIG_DST_BUFFER and stay ABI and API compatible
 
```c++
typedef enum {
    UCC_COLL_ARGS_FLAG_IN_PLACE             = UCC_BIT(0), /*!< If set, the
                                                            output buffer is
                                                            identical to the
                                                            input buffer.*/
    UCC_COLL_ARGS_FLAG_PERSISTENT           = UCC_BIT(1), /*!< If set, the
                                                            collective is
                                                            considered
                                                            persistent.
                                                            Only, the
                                                            persistent
                                                            collective
                                                            can be called
                                                            multiple times with
                                                            the same request.
                                                           */
    UCC_COLL_ARGS_FLAG_COUNT_64BIT          = UCC_BIT(2), /*!< If set, the count
                                                            is 64bit, otherwise,
                                                            it is 32 bit. */
    UCC_COLL_ARGS_FLAG_DISPLACEMENTS_64BIT  = UCC_BIT(3), /*!< If set, the
                                                            displacement is
                                                            64bit, otherwise, it
                                                            is 32 bit. */
    UCC_COLL_ARGS_FLAG_CONTIG_SRC_BUFFER    = UCC_BIT(4), /*!< If set, the src
                                                            buffer is considered
                                                            contiguous.
                                                            Particularly, useful
                                                            for alltoallv
                                                            operation.*/
    UCC_COLL_ARGS_FLAG_CONTIG_DST_BUFFER    = UCC_BIT(5), /*!<If set, the dst
                                                            buffer is considered
                                                            contiguous.
                                                            Particularly, useful
                                                            for alltoallv
                                                            operation. */
    UCC_COLL_ARGS_FLAG_TIMEOUT              = UCC_BIT(6), /*!<If set and the elapsed
                                                            time after @ref ucc_collective_post
                                                            (or @ref ucc_collective_triggered_post)
                                                            is greater than @ref ucc_coll_args_t.timeout,
                                                            the library returns UCC_ERR_TIMED_OUT
                                                            on the calling thread.
                                                            Note, the status is not guaranteed
                                                            to be global on all the processes
                                                            participating in the collective.*/
    UCC_COLL_ARGS_FLAG_MEM_MAPPED_BUFFERS   = UCC_BIT(7)  /*!< If set, both src
                                                            and dst buffers
                                                            reside in a memory
                                                            mapped region.
                                                            Useful for one-sided
                                                            collectives. */
} ucc_coll_args_flags_t;

typedef enum {
    UCC_COLL_ARGS_HINT_OPTMIZE_OVERLAP_CPU  = UCC_BIT(24), /*!< When the flag is
                                                            set, the user
                                                            prefers the library
                                                            to choose an
                                                            algorithm
                                                            implementation
                                                            optimized for the
                                                            best overlap of CPU
                                                            resources. */
    UCC_COLL_ARGS_HINT_OPTMIZE_OVERLAP_GPU  = UCC_BIT(25), /*!< When the flag is
                                                            set, the user
                                                            prefers the library
                                                            to choose an
                                                            algorithm
                                                            implementation
                                                            optimized for the
                                                            best overlap of GPU
                                                            resources. */
    UCC_COLL_ARGS_HINT_OPTIMIZE_LATENCY     = UCC_BIT(26) /*!<  When the flag is
                                                           set, the user prefers
                                                           the library to choose
                                                           an algorithm
                                                           implementation
                                                           optimized for the
                                                           latency. */
    UCC_COLL_ARGS_HINT_CONTIG_SRC_BUFFER    = UCC_COLL_ARGS_FLAG_CONTIG_SRC_BUFFER,
    UCC_COLL_ARGS_HINT_CONTIG_DST_BUFFER.   = UCC_COLL_ARGS_FLAG_CONTIG_DST_BUFFER
} ucc_coll_args_hints_t;
```

**Comment by manjugv** [comment]
@Sergei-Lebedev I'm fine with it. @vspetrov ?

**Comment by BrodyWilliams** [comment]
FWIW, I don't see any issue with this update.

**Review by Sergei-Lebedev — APPROVED** [review]

**Pull request merged**
