### PR TITLE
UTIL: ucs_config_names_search signature

### PR DESCRIPTION
**Pull request by vspetrov**
## What
Fix compilation error in ucc_config_names_search

## Why ?
openucx/ucx#7379

### CODE REVIEW

**Review by lappazos — APPROVED** [review]

**Review by Sergei-Lebedev — APPROVED** [review]

**Review by shimmybalsam — APPROVED** [review]

**Review by bureddy — APPROVED** [review]

**Comment by bureddy** [comment]
@vspetrov  this is breaking compatibility. now need to build and run with before/after UCX change

**Comment by vspetrov** [comment]
> @vspetrov  this is breaking compatibility. now need to build and run with before/after UCX change
> 
> 

@bureddy i don't get it. What breaks compat? I thought i made this pr exactly to keep support for both ucx versions. And detection is automatic.

**Comment by bureddy** [comment]
I mean building UCC with UCX version v1 api but, run time using UCX version api v2.

**Comment by vspetrov** [comment]
> I mean building UCC with UCX version v1 api but, run time using UCX version api v2.

I see, you are right. I think we already had such an issue with UCS cache api changes. I think UCX should detect runtime mismatch, no? Otherwise, UCX introduced the same binary incompat, right?

**Comment by yosefe** [comment]
UCS API (unlike UCP/UCT) does not guarantee binary or API compatibility so need to adjust UCC for changes.
In this case, a better fix would be looping over ucs_config_names_array_t directly, instead of using the helper function ucs_config_names_search()

**Pull request merged**
