### PR TITLE
TEST: Enabled Jenkins CI (for v0.1.x)

### PR DESCRIPTION
**Pull request by artemry-nv**
## What
Enabled Jenkins CI (ported from master branch).

## Why ?
Enabled extended test scenarios.

### CODE REVIEW

**Comment by artemry-nv** [comment]
@Sergei-Lebedev @vspetrov @bureddy do you plan to port this option to v0.1.x branch?
`lt-ucc_test_mpi: unrecognized option '--set_device'`

**Comment by bureddy** [comment]
is CI scripts common for all the releases? why 0.1.x CI trying to use --ser_device option if that is not there in that branch?

**Comment by artemry-nv** [comment]
> is CI scripts common for all the releases? why 0.1.x CI trying to use --ser_device option if that is not there in that branch?

Yes, currently I ported the scripts from master and finding out what is missing (planned to be ported from master) in v0.1.x branch.

**Comment by bureddy** [comment]
is there a way to make Jenkins happy in v1.10.x branch?

**Comment by artemry-nv** [comment]
> is there a way to make Jenkins happy in v1.10.x branch?

I'm reducing test scenarios to the ones operable on v1.10.x branch.

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
@Sergei-Lebedev @vspetrov @bureddy please merge this PR.

**Review by vspetrov — APPROVED** [review]

**Review by bureddy — APPROVED** [review]

**Pull request merged**
