### PR TITLE
Updated pytorch

### PR DESCRIPTION
**Pull request by artemry-nv**
Signed-off-by: artemry-nv <artemry@nvidia.com>

## What
Updated PyTorch.

## Why ?
To support latest PyTorch versions.

### CODE REVIEW

**Comment by artemry-nv** [comment]
CC @Sergei-Lebedev

**Comment by Sergei-Lebedev** [comment]
@artemry-nv looks like there is some issue installing DLRM in CI job

**Comment by artemry-nv** [comment]
@bureddy @manjugv @lappazos please merge

**Review by lappazos — APPROVED** [review]

**Comment by lappazos** [comment]
@vspetrov @manjugv why not merge?

**Review by vspetrov — APPROVED** [review]

**Pull request merged**
