### PR TITLE
TOOLS: support triggered colls in perftest

### PR DESCRIPTION
**Pull request by Sergei-Lebedev**
## What
Add an option to run and benchmark triggered collectives with ucc_perftest

### CODE REVIEW

**Comment by edgargabriel** [comment]
I know this has already been merged, but this commit seems to break compilations on my systems (without any of our changes from the other pr):

make[2]: Entering directory '/home/WORKSPACE/egabriel/tmp/ucc2/tools/perf'
  CXX      ucc_perftest-ucc_perftest.o
  CXX      ucc_perftest-ucc_pt_config.o
  CXX      ucc_perftest-ucc_pt_comm.o
  CXX      ucc_perftest-ucc_pt_cuda.o
  CXX      ucc_perftest-ucc_pt_benchmark.o
  CXX      ucc_perftest-ucc_pt_bootstrap_mpi.o
  CXX      ucc_perftest-ucc_pt_coll.o
  CXX      ucc_perftest-ucc_pt_coll_allgather.o
  CXX      ucc_perftest-ucc_pt_coll_allgatherv.o
  CXX      ucc_perftest-ucc_pt_coll_allreduce.o
  CXX      ucc_perftest-ucc_pt_coll_alltoall.o
  CXX      ucc_perftest-ucc_pt_coll_alltoallv.o
  CXX      ucc_perftest-ucc_pt_coll_barrier.o
  CXX      ucc_perftest-ucc_pt_coll_bcast.o
  CXX      ucc_perftest-ucc_pt_coll_reduce.o
  CXX      ucc_perftest-ucc_pt_coll_reduce_scatter.o
  CXXLD    ucc_perftest
/usr/bin/ld: ucc_perftest-ucc_pt_cuda.o: undefined reference to symbol 'dlsym@@GLIBC_2.2.5'

**Comment by edgargabriel** [comment]
Please ignore previous message, it was the wrong pr

**Comment by manjugv** [comment]
@Sergei-Lebedev Is the idea to measure the latency here or something else?

**Comment by Sergei-Lebedev** [comment]
> @Sergei-Lebedev Is the idea to measure the latency here or something else?

Measure collective time. Internally coll post and triggered coll post uses different routines for some tasks e.g. reduction operations, so latency of collective posted with "regular post" doesn't always reflect latency of the same collective posted using triggered post.

**Comment by manjugv** [comment]
> > @Sergei-Lebedev Is the idea to measure the latency here or something else?
> 
> Measure collective time. Internally coll post and triggered coll post uses different routines for some tasks e.g. reduction operations, so latency of collective posted with "regular post" doesn't always reflect latency of the same collective posted using triggered post.

It is ok for sanity checking but you have to remember that the latency of triggered can be higher because completion really depends on the arrival of the event. If a user is concerned about latency then it is not the correct interface to use. :)

**Review by manjugv — APPROVED** [review]

**Review by vspetrov — APPROVED** [review]

**Pull request merged**
