### PR TITLE
UCC Profile

### PR DESCRIPTION
**Pull request by Sergei-Lebedev**
## What
Profiling MC functions (reduce, multi reduce, alloc) and TL UCP collectives

## How ?
UCC profiling is based on UCS profile. It was extended here to support profiling external libraries https://github.com/openucx/ucx/pull/6827
Supported profiler API:
UCC_PROFILE_FUNC - function profiling
UCC_PROFILE_REQUEST_NEW, UCC_PROFILE_REQUEST_EVENT, UCC_PROFILE_REQUEST_FREE  - capture nb progress.
ucx_read_profile should be user to print profiling results

allreduce profiling example:

accum mode
```
   ucs lib : libucs.so.0
   command : ucc_perftest
   pid     : 51205
   threads : 1  (showing thread 1)

                               NAME    AVG (usec)  TOTAL (usec)      %OVERALL        COUNT               FILE:LINE   FUNCTION                            THREADS
                ucc_mc_reduce_multi      1276.049     571669.90        44.480          448           ucc_mc.c:160    ucc_mc_reduce_multi                 1
                      ucc_mc_memcpy        25.321       5570.68         0.433          220           ucc_mc.c:178    ucc_mc_memcpy                       1
                ucc_collective_init         0.783        347.73         0.027          444         ucc_coll.c:119    ucc_collective_init                 1
            ucc_collective_finalize         0.102         45.60         0.004          444         ucc_coll.c:166    ucc_collective_finalize             1
                       ucc_mc_alloc         3.508         21.05         0.002            6           ucc_mc.c:136    ucc_mc_alloc                        1
    ucp_allreduce_sra_knomial_start           n/a           n/a           n/a          220 allreduce_sra_knomial.c:46     ucc_tl_ucp_allreduce_sra_knomial_start 1
    ucp_reduce_scatter_knomial_star           n/a           n/a           n/a          220 reduce_scatter_knomial.c:180    ucc_tl_ucp_reduce_scatter_knomial_start 1
        ucp_allgather_knomial_start           n/a           n/a           n/a          220 allgather_knomial.c:134    ucc_tl_ucp_allgather_knomial_start  1
```

log mode
```
     1.031  ucc_collective_init 0.615 {                           ucc_coll.c:119  ucc_collective_init()
     0.455      NEWtl_ucp_task {218}                           tl_ucp_coll.h:74   ucc_tl_ucp_get_task()
     0.161  }
     4.079  ucc_collective_finalize 0.046 {                       ucc_coll.c:166  ucc_collective_finalize()
     0.033      FREE {218}                                     tl_ucp_coll.h:81   ucc_tl_ucp_put_task()
     0.014  }
     0.400  ucc_collective_init 0.878 {                           ucc_coll.c:119  ucc_collective_init()
     0.350      NEWtl_ucp_task {219}                           tl_ucp_coll.h:90   ucc_tl_ucp_get_schedule()
     0.094      NEWtl_ucp_task {220}                           tl_ucp_coll.h:74   ucc_tl_ucp_get_task()
     0.200      NEWtl_ucp_task {221}                           tl_ucp_coll.h:74   ucc_tl_ucp_get_task()
     0.235  }
     0.062  ucp_allreduce_sra_knomial_start {219}            allreduce_sra_knomial.c:46   ucc_tl_ucp_allreduce_sra_knomial_start()
     0.047  ucp_reduce_scatter_knomial_star {220}            reduce_scatter_knomial.c:180  ucc_tl_ucp_reduce_scatter_knomial_start()
   414.009  ucc_mc_reduce_multi 2295.741 {                          ucc_mc.c:160  ucc_mc_reduce_multi()
  2295.741  }
    61.841  ucc_mc_reduce_multi 409.746 {                           ucc_mc.c:160  ucc_mc_reduce_multi()
   409.746  }
     0.398  ucc_mc_memcpy 25.815 {                                  ucc_mc.c:178  ucc_mc_memcpy()
    25.815  }
     0.146  ucp_allgather_knomial_start {221}                allgather_knomial.c:134  ucc_tl_ucp_allgather_knomial_start()
     3.573  FREE {220}                                         tl_ucp_coll.h:81   ucc_tl_ucp_put_task()
   767.948  FREE {221}                                         tl_ucp_coll.h:81   ucc_tl_ucp_put_task()
     0.353  ucc_collective_finalize 0.109 {                       ucc_coll.c:166  ucc_collective_finalize()
     0.095      FREE {219}                                     tl_ucp_coll.h:97   ucc_tl_ucp_put_schedule()
     0.014  }
```

### CODE REVIEW

**Comment by artemry-nv** [comment]
bot:retest

**Comment by artemry-nv** [comment]
bot:retest

**Comment by manjugv** [comment]
@vspetrov Add scoping.

**Comment by Sergei-Lebedev** [comment]
> @vspetrov or @Sergei-Lebedev to add scoping.

@manjugv 
added new option --with-profiling to specify components to profile, e.g --with-profiling=core,tl_ucp

**Review by vspetrov — APPROVED** [review]
I would just put profile config into profile.m4 and debug into debug.m4: right now they are kind of grouped together although unrelated

**Comment by manjugv** [comment]
@gvallee Please let us know, if you have comments ..

**Comment by manjugv** [comment]
@Sergei-Lebedev I tested the patch and it looks good. 

 ```
  ucs lib :ucx-install/lib/libucs.so.0
   host    : 
   command : ./osu_oshm_barrier
   pid     : 2445491
   threads : 1  (showing thread 1)

                               NAME    AVG (usec)  TOTAL (usec)      %OVERALL        COUNT               FILE:LINE   FUNCTION                            THREADS
                ucc_collective_init         0.193         22.20         0.008          115         ucc_coll.c:121    ucc_collective_init                 1            
            ucc_collective_finalize         0.109         12.54         0.004          115         ucc_coll.c:169    ucc_collective_finalize             1            
                ucc_mc_reduce_multi         0.780          3.90         0.001            5           ucc_mc.c:141    ucc_mc_reduce_multi                 1            
                       ucc_mc_alloc         0.777          3.89         0.001            5           ucc_mc.c:120    ucc_mc_alloc                        1            
               ucp_barrier_kn_start           n/a           n/a           n/a          112  barrier_knomial.c:110    ucc_tl_ucp_barrier_knomial_start    1            
                ucp_barrier_kn_done           n/a           n/a           n/a          112  barrier_knomial.c:99     ucc_tl_ucp_barrier_knomial_progress 1   
```

1. Should we enable profiling all ranks by default? can we profile a single process by default so we don't overwhelm the filesystem ? Thoughts?
2. Reading profile with ucx_read_profile is weird though convenient. We are creating explicit dependency on ucx.

**Comment by Sergei-Lebedev** [comment]
> I would just put profile config into profile.m4 and debug into debug.m4: right now they are kind of grouped together although unrelated

the idea was to move general ucc config options (such as enable debug and enable profile) from configure.ac to separate file. I think in future we can add something like enable-avx or something similar to that file. Creating separate m4 for each such options seems to be overkill. wdyt?

**Comment by Sergei-Lebedev** [comment]
> 1. Should we enable profiling all ranks by default? can we profile a single process by default so we don't overwhelm the filesystem ? Thoughts?

By default profiling is disabled for all the ranks even if compiled with --enable-profiling. User needs to explicitly set UCC_PROFILE_MODE variable to enable it. So if user wants to profile only single process the cmd line might be

```
export UCC_PROFILE_MODE=accum
mpirun .... user_app.exe
```
and to profile all ranks
```
mpirun -x UCC_PROFILE_MODE=accum user_app.exe
```

Enabling profiling per rank is sometimes ambiguous. What if you have multiple teams with different ranks numbering. 

> 2. Reading profile with ucx_read_profile is weird though convenient. We are creating explicit dependency on ucx.

We have this dependency anyway, strictly speaking it's dependency on ucs since profiler is part of ucs. I think in future we will have ucc native profile read tool, for now I can copy paste ucx_read_profile during install and rename it to ucc_read_profile if you think it's needed

**Comment by gvallee** [comment]
> @gvallee Please let us know, if you have comments ..

I just finished giving it a try at scale: I like it and find it really useful. There is not a single point that i could raise as being a concern or something that would go against my personal preferences. I just like it.

**Review by manjugv — APPROVED** [review]

**Pull request merged**
