### PR TITLE
UCC: pr template and check commit title

### PR DESCRIPTION
**Pull request by Sergei-Lebedev**
## What
Add github pull request template and commits title check similar to UCX

## Why ?
Make automatic commits check

### CODE REVIEW

**Comment by manjugv** [comment]
@Sergei-Lebedev I like the PR. 

Thoughts 
1. Should we make this pre-commit hook ?
2. Should we impose more constraints, so, we make it readable - say 50-60 char limit, no period at the end, separate body from the subject  with blank line ...

**Comment by Sergei-Lebedev** [comment]
1. We can have both precommit hook and CI style check just to protect in case somebody uses git commit --no-verify
2. Agree, adding altogether
Commit subject is 50 char maximum
Commit subject starts with subsystems names, e.g. "UCC/CORE: ...", "UCC/TL/SHARP: ...", "UCC/DOCS: .."
No period at the end of commit subject
Commit subject and commit body separated by blank line
Anything else?

**Review by alex--m — APPROVED** [review]

**Review by vspetrov — APPROVED** [review]

**Comment by Sergei-Lebedev** [comment]
@manjugv added additional checks
allowed names for subsystems defined by regex (note that there is no UCC prefix)

```shell
'^Merge |^((CORE|UTIL|TEST|API|DOCS|TOOLS)|(CL/|TL/|UCX|UCG))+: \w'
```
sample output:
```shell
Dot at the end of title
Bad commit title: 'TEST: dot at the end of line.'
--------------------------------------------------
Commit title is too long: 178
Bad commit title: 'Intentionally very loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong bad title'
--------------------------------------------------
Wrong header
Bad commit title: 'Intentionally bad title'
--------------------------------------------------
Good commit title: 'TEST: PR Template and check commit title'
--------------------------------------------------
```

**Comment by manjugv** [comment]
Looks fine ! Thanks @Sergei-Lebedev

**Review by manjugv — APPROVED** [review]

**Pull request merged**
