### PR TITLE
TL/UCP: fix onesided get

### PR DESCRIPTION
**Pull request by wfaderhold21**
## What
Fixes the ucc_tl_ucp_get_nb() to use the correct callbacks as specified by the UCP API.

## Why ?
Current implementation will result in incorrect execution if used for future algorithms.

### CODE REVIEW

**Review by vspetrov — APPROVED** [review]

**Review by Sergei-Lebedev — APPROVED** [review]
lgtm, but i have question
@wfaderhold21 @vspetrov 
what do you think if we add union to tl_ucp_task
```C
union {
    struct {
        uint32_t        send_posted;
        uint32_t        send_completed;
        uint32_t        recv_posted;
        uint32_t        recv_completed;
        uint32_t        tag;
     } tagged;
    struct {
        uint32_t        put_posted;
        uint32_t        put_completed;
        uint32_t        get_posted;
        uint32_t        get_completed;
    } onesided;
}
```
I think it looks cleaner

**Comment by vspetrov** [comment]
> lgtm, but i have question @wfaderhold21 @vspetrov what do you think if we add union to tl_ucp_task
> 
> ```c
> union {
>     struct {
>         uint32_t        send_posted;
>         uint32_t        send_completed;
>         uint32_t        recv_posted;
>         uint32_t        recv_completed;
>         uint32_t        tag;
>      } tagged;
>     struct {
>         uint32_t        put_posted;
>         uint32_t        put_completed;
>         uint32_t        get_posted;
>         uint32_t        get_completed;
>     } onesided;
> }
> ```
> 
> I think it looks cleaner

i like it.

**Comment by wfaderhold21** [comment]
> lgtm, but i have question @wfaderhold21 @vspetrov what do you think if we add union to tl_ucp_task
> 
> ```c
> union {
>     struct {
>         uint32_t        send_posted;
>         uint32_t        send_completed;
>         uint32_t        recv_posted;
>         uint32_t        recv_completed;
>         uint32_t        tag;
>      } tagged;
>     struct {
>         uint32_t        put_posted;
>         uint32_t        put_completed;
>         uint32_t        get_posted;
>         uint32_t        get_completed;
>     } onesided;
> }
> ```
> 
> I think it looks cleaner

I also like it. @vspetrov @Sergei-Lebedev shall I go ahead and make those changes in this PR?

**Comment by vspetrov** [comment]
@wfaderhold21 yes, lets do in a separate PR

**Pull request merged**
