### PR TITLE
BUILD/ROCM: check ROCm version in configure logic

### PR DESCRIPTION
**Pull request by edgargabriel**
## What
check ROCm version in configure logic

## Why
This allows us to be more accurate when specifying include paths. Reduces the number of warnings generated for the rocm ec component.

### CODE REVIEW

**Review by vspetrov — APPROVED** [review]

**Comment by edgargabriel** [comment]
if possible, this patch would be good to have on the 1.1 branch as well, it reduces the number of warnings in the ec/rocm with rocm 5.2.x tremendously

**Review by Sergei-Lebedev — APPROVED** [review]

**Comment by vspetrov** [comment]
> if possible, this patch would be good to have on the 1.1 branch as well, it reduces the number of warnings in the ec/rocm and mc/rocm components with rocm 5.2.x tremendously

@edgargabriel could you plz open a PR against v1.1.x ?

**Comment by edgargabriel** [comment]
@vspetrov short question: what is the preferred way to do the pr for v1.1, cherry-picking the commit from master or filing a completely new pr? ( I have trouble cherry-picking the commit id, it claims 'fatal: bad object ` for that commit id, which is kind of weird).

**Comment by vspetrov** [comment]
@edgargabriel i've created a cherry-pick https://github.com/openucx/ucc/pull/594

**Pull request merged**
