### PR TITLE
MC: fixed mc reduce multi parameters order

### PR DESCRIPTION
**Pull request by shimmybalsam**
## What
Switch the order between size and count parameters in ucc_mc_reduce_multi function decleration in ucc_mc.h

## Why ?
To fit to the order in which the function is implemeted in ucc_mc.c and in which it is called from ucc_dt_reduce_multi. 

## How ?
Switched size and count.

### CODE REVIEW

**Review by lappazos — APPROVED** [review]

**Review by vspetrov — COMMENTED** [review]
Ok, so if we want to improve readability i would change "size" in the declaration to "n_vectors". It is more clear imho. And then also need to change in implementations for consistency

**Comment by lappazos** [comment]
> Ok, so if we want to improve readability i would change "size" in the declaration to "n_vectors". It is more clear imho. And then also need to change in implementations for consistency

It's not improved readability, it is a mistake that the compiler passed only since both are the same type. I agree, but need to change also ucc_dt_reduce_multi variable name.

**Comment by shimmybalsam** [comment]
> Ok, so if we want to improve readability i would change "size" in the declaration to "n_vectors". It is more clear imho. And then also need to change in implementations for consistency

All changed. Please check.

**Comment by vspetrov** [comment]
bot:retest

**Review by vspetrov — APPROVED** [review]

**Review by Sergei-Lebedev — APPROVED** [review]

**Comment by artemry-nv** [comment]
bot:retest

**Pull request merged**
